---
- hosts: all
  roles:
  - cloudalchemy.prometheus
  vars:
    prometheus_targets:
      node:
      - targets:
        - localhost:9100
        labels:
          env: demosite
dependencies:
  - src: https://github.com/cloudalchemy/ansible-prometheus.git
    scm: git
    version: master
    name: cloudalchemy.prometheus
